version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"   # internal Jenkins port (not exposed publicly)
      - "50000:50000" # for Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8888:80"   # expose Nginx publicly
      # - "443:443" # uncomment if you want SSL termination later
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jenkins

volumes:
  jenkins_home:

