version: "3.8"

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
  docker-data:

services:
  docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: unless-stopped
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: ""  
    volumes:
      - docker-data:/var/lib/docker
    ports:
      - "2375:2375"
    command: ["--host=tcp://0.0.0.0:2375","--storage-driver=overlay2"]

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    networks:
      - jenkins
    expose:
      - "8080"
      - "50000"
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_VERIFY: 0
    volumes:
      - jenkins-data:/var/jenkins_home
    depends_on:
      - docker

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jenkins

